const en = {
  nav: { home:"Home", about:"About", courses:"Courses", faculty:"Faculty", dashboard:"Dashboard", login:"Login / Sign Up", logout:"Logout" },
  language: { switch:"বাংলা" },
  common: { explore:"EXPLORE", all:"All", searchCourses:"Search courses...", viewDetails:"View Details →", noCourses:"No courses found in this category.", exploreCreativity:"Explore creativity", exploreYourCreativity:"Explore your creativity" },
  home: {
    watchStory:"Watch Our Story", coursesTitle:"Our Courses", coursesIntro:"From music to movement, lenses to colors, explore a wide range of creative courses designed for all age groups and skill levels.",
    viewAll:"View All Courses", expertMentors:"Expert Mentors", expertMentorsText:"Learn from experienced professionals",
    creativeCommunity:"Creative Community", creativeCommunityText:"Be part of a vibrant artistic family",
    events:"Events & Showcase", eventsText:"Regular events, exhibitions & recitals",
    personalGrowth:"Personal Growth", personalGrowthText:"Build confidence, discipline and life skills",
    moreThan:"More\nThan a School", students:"Students", courses:"Courses", expertFaculty:"Expert Faculty",
    testimonialsLabel:"WHAT OUR STUDENTS SAY", testimonialsTitle:"Voices from Our Community",
    studentFallback:"Surchobi Student", studentVoicesEmpty:"Student voices will appear here after reviews are submitted and approved.",
    galleryLabel:"GALLERY", galleryTitle:"Moments at\nSurchobi", galleryText:"A glimpse of creativity, learning and expression from our academy.",
    gallerySoon:"Gallery coming soon", gallerySoonText:"Academy moments will appear here after the admin uploads and publishes images."
  },
  hero: {
    musicTitle:"MUSIC", musicSubtitle:"Find Your Sound", danceTitle:"DANCE", danceSubtitle:"Move. Express. Shine",
    photoTitle:"PHOTOGRAPHY", photoSubtitle:"Capture Perspectives", drawingTitle:"DRAWING", drawingSubtitle:"Imagine. Create. Colour.",
    yogaTitle:"YOGA", yogaSubtitle:"Breathe. Balance. Grow.", othersTitle:"OTHERS", othersSubtitle:"Explore More"
  },
  about: { title:"Nurturing Creativity For A Brighter Tomorrow", text:"SURCHOBI is a creative arts academy where passion meets discipline." },
  courses: { allCourses:"All Courses" },
  courseDetail: { notFound:"Course not found", back:"← Back to Courses", defaultDescription:"Explore creativity and build your skills with guidance from our mentors.", about:"About this course", infoUpdated:"Course information will be updated by the academy.", timing:"Class Timing", contactTiming:"Contact the academy for current batch timings.", details:"Course Details", category:"Category", creativeArts:"Creative Arts", contactFees:"Contact the academy for fees, age group and batch availability.", mentors:"MENTORS", learnFaculty:"Learn with our Faculty", facultyMember:"Faculty Member", facultySoon:"Faculty information will be added soon." },
  auth: { createTitle:"Create your account", welcome:"Welcome to Surchobi", join:"Join our creative community.", signInContinue:"Sign in to continue to your dashboard.", fullName:"Full name", yourName:"Your full name", email:"Email", password:"Password", minChars:"Minimum 6 characters", pleaseWait:"Please wait...", createAccount:"Create Account", signIn:"Sign In", forgot:"Forgot password?", newTo:"New to Surchobi?", already:"Already have an account?", forgotTitle:"Forgot Password", sending:"Sending...", sendReset:"Send Reset Link", backLogin:"Back to Login", resetTitle:"Reset Password", newPassword:"New password", confirmPassword:"Confirm password", updating:"Updating...", updatePassword:"Update Password" },
  faculty: { label:"OUR FACULTY", title:"Meet Our Faculty", member:"Faculty Member", specialization:"Creative Arts", bio:"Experienced mentor at Surchobi.", empty:"Faculty information will be added soon." },
  reviews: { yourVoice:"YOUR VOICE", myReview:"My Review", stars:"stars", star:"star", sharePlaceholder:"Share your experience at Surchobi...", submit:"Submit Review", published:"Published", pending:"Pending", longer:"Please write a longer review.", submitted:"Review submitted for approval.", communityVoices:"COMMUNITY VOICES", studentReviews:"Student Reviews", moderationInfo:"Approve reviews to publish them on the homepage.", student:"Student", approve:"Approve", hide:"Hide", delete:"Delete", approved:"Review approved.", hidden:"Review hidden.", deleteConfirm:"Delete this review permanently?", deleted:"Review deleted." },
  gallery: { label:"HOMEPAGE GALLERY", title:"Manage Gallery", description:"Upload academy moments, then publish the ones you want visitors to see.", titlePlaceholder:"Image title (optional)", choose:"Choose image", upload:"Upload Image", uploading:"Uploading...", published:"Published", draft:"Draft / Hidden", hide:"Hide", publish:"Publish", delete:"Delete", gallery:"Gallery", untitled:"Untitled", selectImage:"Please select an image.", imageOnly:"Please choose an image file.", sizeLimit:"Gallery image must be 10MB or smaller.", uploaded:"Gallery image uploaded. Publish it when ready.", uploadFailed:"Could not upload gallery image.", publishedMsg:"Gallery image published.", hiddenMsg:"Gallery image hidden.", deleteConfirm:"Delete this gallery image permanently?", deleted:"Gallery image deleted." },
  websiteEditor: { label:"WEBSITE", title:"Website Editor", eyebrow:"Hero eyebrow", heroTitle:"Hero title", heroSubtitle:"Hero subtitle", heroText:"Hero text", imageUrl:"Music hero image URL", save:"Save Website Settings", saved:"Website settings saved on this device." },
  notices: { label:"NOTICE BOARD", title:"Notices", titlePlaceholder:"Notice title", contentPlaceholder:"Write the notice...", publish:"Publish Notice", delete:"Delete", required:"Title and notice content are required.", published:"Notice published.", deleteConfirm:"Delete this notice?", deleted:"Notice deleted." },
  fees: { label:"OFFLINE FEE RECORDS", title:"Fee Records", description:"Record payments made offline. This website does not process any money or online transactions.", selectStudent:"Select student", amountPlaceholder:"Amount for record only", notPaid:"Not Paid", paidOffline:"Paid Offline", partiallyPaidOffline:"Partially Paid Offline", save:"Save Record", student:"Student", required:"Select student and month.", saved:"Fee record saved. No online payment is involved." },
  attendance: { label:"ATTENDANCE", title:"Mark Attendance", selectStudent:"Select student", selectBatch:"Select batch", present:"Present", absent:"Absent", late:"Late", save:"Save Attendance", student:"Student", batch:"Batch", required:"Select a student and batch.", saved:"Attendance saved." },
  enrollment: { label:"STUDENT ENROLLMENT", title:"Enrollments", selectStudent:"Select student", selectCourse:"Select course", selectBatch:"Select batch", enrollStudent:"Enroll Student", student:"Student", course:"Course", batch:"Batch", active:"active", required:"Select student, course and batch.", success:"Student enrolled successfully." },
  management: { courseManagement:"COURSE MANAGEMENT", courses:"Courses", courseName:"Course name", category:"Category", courseDescription:"Course description", addCourse:"Add Course", noCategory:"No category", noDescription:"No description", delete:"Delete", courseRequired:"Course name is required.", courseAdded:"Course added.", deleteCourse:"Delete this course?", courseDeleted:"Course deleted.", batchManagement:"BATCH MANAGEMENT", batches:"Batches", batchName:"Batch name", selectCourse:"Select course", selectTeacher:"Select teacher", teacher:"Teacher", scheduleExample:"Schedule, e.g. Sat 5 PM", createBatch:"Create Batch", batchRequired:"Batch name and course are required.", batchCreated:"Batch created.", teacherTba:"Teacher TBA", timingTba:"Timing TBA" },
  people: { studentDirectory:"STUDENT DIRECTORY", teacherDirectory:"TEACHER DIRECTORY", students:"Students", teachers:"Teachers", unnamed:"Unnamed", noPhone:"No phone number", noneFound:"No {type}s found yet." },
  profile: { details:"PROFILE DETAILS", myProfile:"My Profile", fullName:"Full name", phone:"Phone", save:"Save Profile", saved:"Profile saved successfully." },
  teaching: { label:"TEACHING", myBatches:"My Batches", course:"Course", timingTba:"Timing TBA", students:"students", noneAssigned:"No batches are assigned to you yet." },
  learning: { label:"MY LEARNING", myCourses:"My Courses", course:"Course", batch:"Batch", timingTba:"Timing TBA", notEnrolled:"You are not enrolled in a course yet.", recentAttendance:"RECENT ATTENDANCE", noticeBoard:"NOTICE BOARD" },
  dashboard: { overview:"Overview", myProfile:"My Profile", myLearning:"My Learning", myReview:"My Review", reviews:"Reviews", gallery:"Gallery", students:"Students", teachers:"Teachers", courses:"Courses", batches:"Batches", enrollments:"Enrollments", feeRecords:"Fee Records", myBatches:"My Batches", attendance:"Attendance", notices:"Notices", website:"Website", logout:"Log out", tagline:"Learn • Create • Express", welcomeBack:"Welcome back,", welcome:"Welcome,", ready:"Your Surchobi profile is ready.", yourProfile:"YOUR PROFILE", yourName:"Your Name", editProfile:"Edit Profile", there:"there", user:"User", artist:"Artist" },
  footer: {}
};
export default en;