name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use preinstalled Node.js
        run: node --version && npm --version
      - run: npm install
      - run: npm run ci
